# Generated by Django 3.2.25 on 2024-03-12 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restfulapi', '0001_initial'),
    ]

    operations = [
    ]
