# Generated by Django 3.2.25 on 2024-03-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restfulapi', '0003_music'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Music',
        ),
    ]
