# Generated by Django 3.2.25 on 2024-03-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfulapi', '0005_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_coach_'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewTeamList',
            fields=[
                ('year_founded', models.IntegerField()),
                ('team_name', models.TextField()),
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=255)),
                ('num_champion', models.IntegerField()),
                ('num_player', models.IntegerField()),
                ('coach_name', models.TextField()),
                ('stadium_name', models.TextField()),
                ('introduce', models.TextField()),
            ],
            options={
                'db_table': 'view_team_list',
                'managed': False,
            },
        ),
    ]
