# Generated by Django 3.2.25 on 2024-03-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfulapi', '0006_viewteamlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducePlayerDetail',
            fields=[
                ('name', models.TextField()),
                ('game_season', models.TextField()),
                ('team_name', models.TextField()),
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('game_id', models.IntegerField(blank=True, null=True)),
                ('team_id', models.IntegerField(blank=True, null=True)),
                ('game_played_count', models.IntegerField(blank=True, null=True)),
                ('min_played', models.FloatField(blank=True, null=True)),
                ('points', models.FloatField(blank=True, null=True)),
                ('field_goals_made', models.FloatField(blank=True, null=True)),
                ('field_goals_attempted', models.FloatField(blank=True, null=True)),
                ('field_goals_percentage', models.FloatField(blank=True, null=True)),
                ('number_3_points_goal_made', models.FloatField(blank=True, db_column='3_points_goal_made', null=True)),
                ('number_3_points_goal_attempted', models.FloatField(blank=True, db_column='3_points_goal_attempted', null=True)),
                ('number_3_points_goal_percentage', models.FloatField(blank=True, db_column='3_points_goal_Percentage', null=True)),
                ('free_throws_made', models.FloatField(blank=True, null=True)),
                ('free_throws_attempted', models.FloatField(blank=True, null=True)),
                ('free_throw_percentage', models.FloatField(blank=True, null=True)),
                ('offensive_rebounds', models.FloatField(blank=True, null=True)),
                ('defensive_rebounds', models.FloatField(blank=True, null=True)),
                ('total_rebounds', models.FloatField(blank=True, null=True)),
                ('assists', models.FloatField(blank=True, null=True)),
                ('turnovers', models.FloatField(blank=True, null=True)),
                ('steels', models.FloatField(blank=True, null=True)),
                ('blocks', models.FloatField(blank=True, null=True)),
                ('personal_fouls', models.FloatField(blank=True, null=True)),
                ('fantacy_points', models.FloatField(blank=True, null=True)),
                ('doubles_doubles', models.FloatField(blank=True, null=True)),
                ('triple_doubles', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'get_player_detail_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewGameList',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('game_season', models.TextField()),
                ('stadium_id', models.IntegerField()),
                ('team_home_id', models.IntegerField()),
                ('team_away_id', models.IntegerField()),
                ('game_date', models.DateField(blank=True, null=True)),
                ('score_winner', models.IntegerField()),
                ('score_loser', models.IntegerField()),
                ('home_team', models.TextField()),
                ('away_team', models.TextField()),
                ('stadium_name', models.TextField()),
            ],
            options={
                'db_table': 'view_game_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewMvpPlayerList',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('mvp_get_count', models.IntegerField(blank=True, null=True)),
                ('jersey_number', models.IntegerField()),
                ('age', models.TextField()),
                ('guard_position', models.TextField()),
                ('country', models.TextField()),
                ('salary', models.TextField()),
            ],
            options={
                'db_table': 'view_mvp_player_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewPlayerList',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('jersey_number', models.IntegerField()),
                ('team_name', models.TextField()),
                ('guard_position', models.TextField()),
                ('height', models.TextField()),
                ('weight', models.TextField()),
                ('last_attended', models.TextField()),
                ('country', models.TextField()),
                ('salary', models.TextField()),
                ('introduce', models.TextField()),
                ('mvp_times', models.IntegerField()),
            ],
            options={
                'db_table': 'view_player_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewPlayerSalaryList',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('jersey_number', models.IntegerField()),
                ('team_name', models.TextField()),
                ('guard_position', models.TextField()),
                ('country', models.TextField()),
                ('salary', models.TextField()),
                ('salary_rank', models.IntegerField()),
                ('salary_per_rank', models.IntegerField()),
            ],
            options={
                'db_table': 'view_player_salary_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewSeasonMvpList',
            fields=[
                ('season_id', models.IntegerField(primary_key=True, serialize=False)),
                ('season_year', models.TextField()),
                ('player_id', models.IntegerField()),
                ('champion_teamid', models.IntegerField()),
                ('mvp', models.TextField()),
                ('mvp_player', models.TextField()),
                ('champion_team', models.TextField()),
            ],
            options={
                'db_table': 'view_season_mvp_list',
                'managed': False,
            },
        ),
    ]
